#!/usr/bin/env bash

#
# Install NCrystal and OpenMC in a conda environment in Ubuntu/Mint/etc distros
#

# Install prerequisites
# sudo apt install -y git g++ cmake libhdf5-dev libpng-dev curl xcrysden 
# sudo apt install -y --no-install-recommends libfftw3-dev quantum-espresso
# sudo apt install -y gfortran
# sudo apt install -y emacs-gtk mc nedit vim
# 
# curl --output anaconda.sh https://repo.anaconda.com/archive/Anaconda3-2023.03-Linux-x86_64.sh
# chmod +x anaconda.sh
# ./anaconda.sh

# Create installation directory
mkdir openmc_ncrystal_vm
cd openmc_ncrystal_vm

conda create -y --name openmc_ncrystal_vm python=3.9
source ~/anaconda3/etc/profile.d/conda.sh

conda activate openmc_ncrystal_vm
conda install -y pip  jupyterlab
conda install -y -c conda-forge pyside2

# Install NCrystal
git clone https://github.com/mctools/ncrystal.git
cd ncrystal
git checkout develop
cd ..
mkdir build_ncrystal 
cd build_ncrystal
cmake ../ncrystal -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX  -DNCRYSTAL_BUILTIN_PLUGINS="XuShuqi7:MagScat::main;highness-eu:SANSND::main"
make -j 2
make install
source $CONDA_PREFIX/setup.sh
export LD_LIBRARY_PATH=
ncrystal_inspectfile --test
cd ../

# Install MCPL
git clone https://github.com/mctools/mcpl.git 
mkdir build_mcpl 
cd build_mcpl
cmake ../mcpl  -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
make -j 2
make install
cd ../


# Install OpenMC
git clone --recurse-submodules https://github.com/openmc-dev/openmc.git
cd openmc
git checkout develop
cd ../
mkdir build_openmc 
cd build_openmc
cmake ../openmc -DOPENMC_USE_NCRYSTAL=on -DOPENMC_USE_MCPL=on -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
make -j 2 
make install
cd ../openmc
pip install .
python -c "import openmc; print(openmc.Material.from_ncrystal('Al_sg225.ncmat'))"
cd ../

pip install openmc-plotter

pip install ipympl matplotlib spglib gemmi ase pymatgen cif2cell

conda install -y -c conda-forge pyne

# Install NJOY
git clone https://github.com/njoy/NJOY2016.git
mkdir build_njoy
cd build_njoy
cmake ../NJOY2016/ -Dstatic_libraries=ON   -Dstatic_njoy=ON -DCMAKE_EXE_LINKER_FLAGS=-static -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX  
make -j 2
make install
cd ..

# Install OpenMC data (ENDF/B-VIII.0 library)
wget -O endf8.xz https://anl.box.com/shared/static/uhbxlrx7hvxqw27psymfbhi7bx7s6u6a.xz && tar -xJf endf8.xz
