#!/usr/bin/env bash

source ~/anaconda3/etc/profile.d/conda.sh
conda activate tsl_env
source $CONDA_PREFIX/setup.sh
export LD_LIBRARY_PATH=

cd ~/tsl_software
cd mcpl
git pull
cd ../build_mcpl
cmake ../mcpl  -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
make -j 2
make install
cd ..

cd ncrystal
git checkout develop
git pull
cd ../build_ncrystal
cmake ../ncrystal -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX  -DNCRYSTAL_BUILTIN_PLUGINS="XuShuqi7:MagScat::main;highness-eu:SANSND::main"
make -j 2
make install
cd ..

cd openmc
git pull # In case we need to update an older VM
git checkout 6561838 # Do not update after May 15th.
cd ../build_openmc
cmake ../openmc -DOPENMC_USE_NCRYSTAL=on -DOPENMC_USE_MCPL=on -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
make -j 2 
make install
cd ../openmc
pip install .
cd ..
