#!/usr/bin/env bash

source ~/anaconda3/etc/profile.d/conda.sh
conda activate tsl_env
source $CONDA_PREFIX/setup.sh
export LD_LIBRARY_PATH=

cd ~/tsl_software
cd mcpl
git pull
cd ../build_mcpl
make -j 2
make install
cd ..

cd ncrystal
git checkout develop
git pull
cd ../build_ncrystal
make -j 2 
make install
cd ..

cd openmc
git pull
cd ../build_openmc
make -j 2
make install
cd ../openmc
pip install .
cd ..
